#include "../../GUI.h"

lv_obj_t *GUI_Image__bottomLayer__bgImage;
lv_obj_t *GUI_Panel__topLayer__sideBar;
lv_obj_t *GUI_Button__topLayer__homeButton;
lv_obj_t *GUI_Label__topLayer__homeLabel;
lv_obj_t *GUI_Button__topLayer__alarmButton;
lv_obj_t *GUI_Label__topLayer__alarmLabel;
lv_obj_t *GUI_Button__topLayer__settingButton;
lv_obj_t *GUI_Label__topLayer__settingLabel;
lv_obj_t *GUI_Button__topLayer__wifiButton;
lv_obj_t *GUI_Label__topLayer__wifiLabel;
lv_obj_t *GUI_Panel__topLayer__selIndicator;

lv_obj_t *GUI_Screen__splashScreen;

lv_obj_t *GUI_Screen__mainScreen;
lv_obj_t *GUI_Container__mainScreen__timeContainer;
lv_obj_t *GUI_Label__mainScreen__timeLabel;
lv_obj_t *GUI_Label__mainScreen__dayLabel;
lv_obj_t *GUI_Label__mainScreen__dateLabel;
lv_obj_t *GUI_Panel__mainScreen__weatherPanel;
lv_obj_t *GUI_Label__mainScreen__locationLabel;
lv_obj_t *GUI_Label__mainScreen__tempLabel;
lv_obj_t *GUI_Image__mainScreen__wthIcon;
lv_obj_t *GUI_Label__mainScreen__wthLabel;
lv_obj_t *GUI_Label__mainScreen__minMaxLabel;
lv_obj_t *GUI_Line__mainScreen__dividerLine;
lv_obj_t *GUI_Label__mainScreen__fcLabel;
lv_obj_t *GUI_Container__mainScreen__fcContainer;
lv_obj_t *GUI_Container__mainScreen__fcPanel[10];
lv_obj_t *GUI_Image__mainScreen__fcWthIcon[10];
lv_obj_t *GUI_Label__mainScreen__fcTimeLabel[10];
lv_obj_t *GUI_Label__mainScreen__fcTempLabel[10];

lv_obj_t *GUI_Screen__alarmScreen;

lv_style_t GUI_Style__defaultBgStyle;
lv_style_t GUI_Style__bgImageStyle;
lv_style_t GUI_Style__timeStyle;
lv_style_t GUI_Style__dateDispStyle;
lv_style_t GUI_Style__defaultPanelStyle;
lv_style_t GUI_Style__tempDispStyle;
lv_style_t GUI_Style__wthIconStyle;
lv_style_t GUI_Style__wthLabelStyle;
lv_style_t GUI_Style__lineStyle;
lv_style_t GUI_Style__fcWthIconStyle;
lv_style_t GUI_Style__fcTempStyle;
lv_style_t GUI_Style__fcTempStyle;
lv_style_t GUI_Style__sideBarStyle;
lv_style_t GUI_Style__sideButStyle;
lv_style_t GUI_Style__sideTextStyle;
lv_style_t GUI_Style__sideSelIndStyle;
